### ISSUE TITLE
Missing from https://github.com/Caraxi/MyPlugins/blob/main/pluginmaster.json

### ISSUE THREAD

**Issue by ibigfire** [Caraxi/SecretTweaks#1]
Is this supposed to be a part of your plugins?  Was interested in checking it out, but it doesn't seem to be a part of your plugin list.

Maybe I'm just missing whatever the secret is supposed to be...

**Comment by Caraxi** [comment]
It's not a standalone plugins, you have to download it and add it to Simple Tweaks' Tweak Providers

**Comment by ibigfire** [comment]
Ah gotcha, no way to just link to here as a tweak provider like the plugin repositories, I need to download it locally and add it, I see.  I'm guessing it won't auto update in that case either then.  Okay, thank you for the info!
